apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  name: canaries.flagger.app
spec:
  appliesToWorkloads:
    - podspecworkload.standard.oam.dev
    - deployments.apps
  definitionRef:
    name: canaries.flagger.app
  workloadRefPath: spec.targetRef
  revisionEnabled: true
---
apiVersion: core.oam.dev/v1alpha2
kind: WorkloadDefinition
metadata:
  name: deployments.apps
spec:
  definitionRef:
    name: deployments.apps