apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: rollout-demo-app
spec:
  workload:
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: rollout-demo-app
    spec:
      selector:
        matchLabels:
          app: rollout-demo-app
      template:
        metadata:
          labels:
            app: rollout-demo-app
        spec:
          containers:
            - image: stefanprodan/podinfo:4.0.6
              name: metrics-provider
              ports:
                - name: http
                  containerPort: 8080
