apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: rollout-demo-app
spec:
  workload:
    apiVersion: standard.oam.dev/v1alpha1
    kind: PodSpecWorkload
    metadata:
      labels:
        app: rollout-demo-app
    spec:
      podSpec:
        containers:
          - image: stefanprodan/podinfo:5.0.2
            name: metrics-provider
            ports:
              - name: http
                containerPort: 8080