apiVersion: core.oam.dev/v1beta1
kind: AppDeployment
metadata:
  name: example-appdeploy
spec:
  traffic:
    hosts:
      - example-app.example.com
    gateways:
      - example-app-gateway
    http:
      - weightedTargets:
          - revisionName: example-app-v1
            componentName: testsvc
            port: 8000
            weight: 50
          - revisionName: example-app-v2
            componentName: testsvc
            port: 80
            weight: 50

  appRevisions:
    - revisionName: example-app-v1
      placement:
        - distribution:
            replicas: 1

    - revisionName: example-app-v2

      placement:
        - distribution:
            replicas: 1
