apiVersion: core.oam.dev/v1beta1
kind: AppDeployment
metadata:
  name: example-appdeploy
spec:
  appRevisions:
    - revisionName: example-app-v1

      placement:
        - distribution:
            replicas: 1

    - revisionName: example-app-v2

      placement:
        - distribution:
            replicas: 1
